pipeline:
  build:
    image: node:6.11.3
    commands:
      - npm install -quiet --silent

  docker:
    image: plugins/docker
    registry: sodimaccr.azurecr.io
    username: sodimaccr
    repo: sodimaccr.azurecr.io/ramen-doc
    tags:
      - latest
      - c-${DRONE_COMMIT_SHA}
      - b-${DRONE_BUILD_NUMBER}
    secrets: [ docker_password ]

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone_deployments
    icon_emoji: ":robot_face:"
    when:
      status: [ success, failure ]