pipeline:
  build:
    image: node:6.11.3
    commands:
      - npm install -quiet --silent

  docker:
    image: plugins/docker
    registry: sodimaccr.azurecr.io
    username: sodimaccr
    repo: sodimaccr.azurecr.io/ramen-doc
    tags:
      - latest
      - c-${DRONE_COMMIT_SHA}
      - b-${DRONE_BUILD_NUMBER}
    secrets: [ docker_password ]

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: ramen-doc
    icon_emoji: ":robot_face:"
    template: >
      {{#success build.status}}
        [{{repo.name}}] @{{build.author}} build {{build.number}} succeeded. Good job.
      {{else}}
        [{{repo.name}}] @{{build.author}} build {{build.number}} failed. Fix me please.
      {{/success}}